use std::fmt::Error;

#[tokio::main]
async fn main() -> Result<(), Error> {
    println!("Hello world.");

    Ok(())
}
